#!/bin/sh
export MENDELEY_BASE=/app/extra
export MENDELEY_BIN=/app/extra/bin/mendeleydesktop
export MENDELEY_LIB=/app/extra/lib
export MENDELEY_BUNDLED_CPP_LIB=/app/extra/lib/cpp
export MENDELEY_BUNDLED_SSL_LIB=/app/extra/lib/ssl
export MENDELEY_BUNDLED_QT_LIBRARY=/app/extra/lib/qt
export MENDELEY_BUNDLED_QT_PLUGIN=/app/extra/plugins/qt/plugins
export MENDELEY_BUNDLED_QT_PLUGIN_PATH=/app/extra/plugins/qt/plugins
export LD_LIBRARY_PATH=/app/extra/lib/ssl:/app/extra/lib/qt:/app/extra/lib:/app/lib
exec /app/extra/bin/mendeleydesktop "$@"
